server:
  servlet:
    context-path: /shiro.demo
    session.timeout: 3600
spring:
  profiles:
    active: freemarker
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    initialSize: 3 
    minIdle: 2
    maxActive: 60
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    removeAbandoned: true
    removeAbandonedTimeout: 120
    logAbandoned: false
    filters: stat

mybatis.mapper-locations: classpath:modify/shiro/demo/common/mapper/*.xml
